### ISSUE TITLE
The app shuts down by clicking on "Paramètres"

### ISSUE THREAD

**Issue by JulieKocianova** [simde-utc/payutc-mobile#164]
**Describe the bug**
The app shuts down immediately as touch the "paramètres" button on a phone with Android 7.0.  

**To reproduce the bug**
Sign in. Touch "paramètres". 

**Expected behavior**
The appearance of a parameters window for the app.  

**Smartphone :**
 - Device: Honor 8
 - OS: EMUI 5.0.1 (Android)
 - Version 7.0.

**Comment by aarrtthhuurr** [comment]
Fixed!
