### ISSUE TITLE
Add "semestre" to history suggestions

### ISSUE THREAD

**Issue by JulieKocianova** [simde-utc/payutc-mobile#166]
**Is your feature request related to a problem? Please describe.**
I would like to see the history stats from a particular semester. 

**Describe the solution you'd like**
Add "semestre" to history suggestion, in which case the history stats would be shown from the beginning of the semester.

**Comment by aarrtthhuurr** [comment]
It will be done soon! :) We'll probably replace the _Month_ filter by that. 

If someone wants to do it, the _Portail des Associations_ provides the current semester beginning: https://assos.utc.fr/api/v1/semesters/current

**Comment by aarrtthhuurr** [comment]
Added in v.1.1.0 :)
