### ISSUE TITLE
Monde à l'envers

### ISSUE THREAD

**Issue by AymanL** [simde-utc/payutc-mobile#252]
![74789173_586538615412528_3871485208536547328_n](https://user-images.githubusercontent.com/40838419/68602682-1402d180-04a7-11ea-9b45-3191defd0350.jpg)

C'est chelou d'avoir "cancel" en bleu et "let's go" en rouge sachant qu'en plus d'habitude le OK est à gauche alors que là c'est l'inverse

Force à vous la team

**Comment by NastuzziSamy** [comment]
Thank you for the report @AymanL  :) 
@aarrtthhuurr can you check this and all other popups ?

**Comment by aarrtthhuurr** [comment]
Hello! 
Merci du retour :)

Pour les Alertes, on a suivi les [guidelines d'iOS](https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/), notamment dans ce cas : 

> Place buttons where people expect them. In general, buttons people are most likely to tap should be on the right. Cancel buttons should always be on the left.
