### ISSUE TITLE
Text Selection color same as text

### ISSUE THREAD

**Issue by MercierCorentin** [simde-utc/payutc-mobile#78]
**Describe the bug**
See screenshot.

**To Reproduce**
Select some text in any int or text field.

**Expected behavior**
The selection color should be different from the text.

**Screenshots**
![Screenshot_20190810-160605](https://user-images.githubusercontent.com/46066895/62822892-1d1f9200-bb8a-11e9-996f-e60490548d6e.png)

**Smartphone:**
 - Device: Motorola G5
 - OS: Android
 - Version: 8.1.0

**Comment by aarrtthhuurr** [comment]
Thanks for reporting! 
It does not happen on iOS, I'll check why.

**Comment by NastuzziSamy** [comment]
@aarrtthhuurr this is why: https://facebook.github.io/react-native/docs/text#selectioncolor (it only happens on Android)
