### ISSUE TITLE
Keyboard Hiding input on Android

### ISSUE THREAD

**Issue by MercierCorentin** [simde-utc/payutc-mobile#81]
**Describe the bug**
See title.

**To Reproduce**
Write something in an input located at the bottom of the screen.

**Expected behavior**
The field shouldn't be hidden by the ketboard.

**Screenshots**
![Screenshot_20190810-163758](https://user-images.githubusercontent.com/46066895/62823099-57d6f980-bb8d-11e9-90ca-be60e932f3a2.png)
![Screenshot_20190810-163806](https://user-images.githubusercontent.com/46066895/62823100-59082680-bb8d-11e9-9507-30a68711682c.png)

**Smartphone (please complete the following information):**
 - Device: Motorola G5
 - OS: Android
 - Version: 8.1.0

**Helpful**
https://github.com/APSL/react-native-keyboard-aware-scroll-view#android-support

**Comment by NastuzziSamy** [comment]
Only happens with Expo
