### ISSUE TITLE
Show a pop-up confirmation just before doing a Transfer

### ISSUE THREAD

**Issue by aarrtthhuurr** [simde-utc/payutc-mobile#93]
To avoid wrong transfers, we could add a basic confirmation pop-up after the user presses "Transfer..." button in TransferScreen.

For example: "Do you confirm you transfer of xxx€ to yyy? [Yeah, let's go!] [Cancel]"

**Comment by NastuzziSamy** [comment]
Maybe set a full screen ? So we avoid modals

**Comment by aarrtthhuurr** [comment]
Why not, or maybe just an Alert with buttons ?
